### ISSUE TITLE
What’s the best web framework

### ISSUE THREAD

**Issue by jouni** [samiheikki/ama#1]
What is the best framework currently in your opinion, and why?

**Comment by samiheikki** [comment]
Thanks @jouni for being the first brave one to ask a question! I have been battling with this question a lot, but IMO it is [Vue.js](http://vuejs.org/). Vue is a quite simplistic web framework, so you can use either in an existing application (for example helping with data binding) or create a new app from group up. I like how it combines the simplicity of Angular 1.x but is combined with the performance of React.

### Performance
Vue is fast. In some cases it is even faster than React [source](http://vuejs.org/v2/guide/comparison.html#Performance-Profiles).

### Almost #usetheplatform
I like how Vue components reminds me of Polymer elements (but not having to import polyfills).

### Documentation
From my experience, Vue's [documentation](http://vuejs.org/v2/guide/) is the best one so far. The documentation is divided by use cases (bindings, list rendering, event handling, transitions and so on...) which gives the developer a clear way of finding what one looked for. Although it might not be friendly for a developer just starting to learn webdev.

### PS
2 days ago I heard from a friend about a new framework called [Svelte](https://github.com/sveltejs/svelte). He said it to be Vue.js of 2017. Will be the next framework I look into.
